Joss corrections issue #139 - native python install.
alan-turing-institute/Palaeoanalytics pull request #142
Opened 2021-11-11 18:57 UTC by JasonGellis

2021-11-12 12:14 UTC, JasonGellis commented
@crangelsmith Same issues as previous PR. Will discuss on Tuesday.

2021-11-16 09:45 UTC, crangelsmith approved these changes

2021-11-16 11:45 UTC, crangelsmith requested changes

2021-11-16 11:45 UTC, crangelsmith commented on README.md
> +**Note**: For Mac users we recommend an OS versions=> 10.14 to prevent build problems. For some OS (e.g. Mojave OSX), the OpenCV installation can take too long, if this is the case you can also insta
Remove this, is not necessary anymore.

2021-11-19 13:12 UTC, merged